### ISSUE TITLE
Changes to the Makefile

### ISSUE THREAD

**Issue by nirvine** [djthorpe/go-rotel#16]
I would love to use this as the alternatives mentioned above have been depreciated. The fork of roteltcp which is "active" does not work for me. 
I have HA Core installed on a RPi5, connected to a Rotel A14 via RS232-USB cable. The Rotel also has a wired ethernet connection. Mosquitto MQTT broker is running in Docker. 

I have generated a Docker token, and installed Go on the RPi. 
When I try to build the repo, I get "unauthorized: unauthenticated: User cannot be authenticated with the token provided"

Which lines do I need to change in the Makefile to allow this to work?

**Comment by djthorpe** [comment]
Hi Narelle, sorry about the issues you are having. You shouldn't need to build this repo unless you are wanting to update the features. You can simply pull the existing docker image. For Intel processors,
```
docker pull ghcr.io/djthorpe/rotel-linux-x86_64:1.0.8
```

For ARM:
```
docker pull ghcr.io/djthorpe/rotel-linux-aarch64:1.0.7
```

Once you have a package locally, you then run it like this, replacing the name of the docker image, the MQTT address and the USB port that your amplifier is connected to:

```
docker run --rm --name rotel --device=/dev/ttyUSB1 \
  ghcr.io/djthorpe/ghcr.io/djthorpe/rotel-linux-x86_64:1.0.8 \
  rotel -mqtt localhost:1883 -tty /dev/ttyUSB1
```

Once this is running, you should be able to create a new card in Home Assistant like the one in the README for basic amplifier control. Let me know if this is working for you. It's very basic and I should really add the remaining features I mentioned in the README file. Let me know how it goes for you.

**Comment by djthorpe** [comment]
....and just on the message `unauthorized: unauthenticated: User cannot be authenticated with the token provided` this is likely because the Makefile includes my repository. you can set the following environment variables as part of the make process to change the repo location:

```
DOCKER_REGISTRY := "ghcr.io"
DOCKER_USER := "djthorpe"
DOCKER_REPOSITORY := "${DOCKER_USER}/go-rotel"
```

So for example, if you forked this repository into your own account on github,
```
git clone git@github.com:nirvine/go-rotel.git
cd go-rotel
DOCKER_USER=nirvine make docker
```

This MIGHT work, if you want to build it for yourself. And if you add any features, I always appreciate pull requests.

**Comment by nirvine** [comment]
Thank you for replying so quickly. 
I am unlikely to add anything, as I am not a programmer - I am a determined user. 
I ran the command for arm64 and got the following message: 

> 1.0.7: Pulling from djthorpe/rotel-linux-aarch64
> Digest: sha256:0792afccefc09f72b3ae4862e2d9a7db5f25295e3c20f77c3af6fe52d26a3c20
> Status: Image is up to date for ghcr.io/djthorpe/rotel-linux-aarch64:1.0.7
> ghcr.io/djthorpe/rotel-linux-aarch64:1.0.7

But the second command to run the container gives 

> MQTT: Connection refused

I am running eclipse-mosquitto with no user control, on port 1883.

**Comment by djthorpe** [comment]
OK, you should be able to see in either the logs for MQTT why it is refusing the connection. Maybe it requires a username/password?

**Comment by nirvine** [comment]
I had set a username and password in MQTT Integration of Home Assistant. the logs for MQTT refers to 'u'hass (the username  entered).

It is a bit hard to identify requests because Portainer seems to obfuscate names. 

> 2024-10-13T08:59:53.973136842Z 1728809993: mosquitto version 2.0.19 starting
> 
> 2024-10-13T08:59:53.982171435Z 1728809993: Config loaded from /mosquitto/config/mosquitto.conf.
> 
> 2024-10-13T08:59:53.982184861Z 1728809993: Opening ipv4 listen socket on port 1883.
> 
> 2024-10-13T08:59:53.982187583Z 1728809993: Opening ipv6 listen socket on port 1883.
> 
> 2024-10-13T08:59:53.982190009Z 1728809993: mosquitto version 2.0.19 running
> 
> 2024-10-13T09:01:04.851964715Z 1728810064: New connection from 127.0.0.1:59631 on port 1883.
> 
> 2024-10-13T09:01:04.864209011Z 1728810064: New client connected from 127.0.0.1:59631 as 0Qyp11RFKWJSiVKKxM59Tw (p2, c1, k60).
> 
> 2024-10-13T09:04:38.475657148Z 1728810278: New connection from 127.0.0.1:35847 on port 1883.
> 
> 2024-10-13T09:04:38.475773128Z 1728810278: New client connected from 127.0.0.1:35847 as 3jorEUPxTdrHQXaUIlboLb (p2, c1, k60, u'hass').
> 
> 2024-10-13T09:04:38.475936348Z 1728810278: Client 3jorEUPxTdrHQXaUIlboLb disconnected.
> 
> 2024-10-13T09:05:01.842486943Z 1728810301: Client 0Qyp11RFKWJSiVKKxM59Tw disconnected.
> 
> 2024-10-13T09:05:01.851640760Z 1728810301: New connection from 127.0.0.1:52229 on port 1883.
> 
> 2024-10-13T09:05:01.855922189Z 1728810301: New client connected from 127.0.0.1:52229 as 4rBigEXpaZiaBhE3MRyytC (p2, c1, k60, u'hass').
> 
> 2024-10-13T09:05:28.912132975Z 1728810328: Client 4rBigEXpaZiaBhE3MRyytC closed its connection.
> 
> 2024-10-13T09:05:40.304793603Z 1728810340: New connection from 127.0.0.1:59695 on port 1883.

**Comment by djthorpe** [comment]
Ok I could add in the ability to set credentials in go-rotel if that would help.

**Comment by nirvine** [comment]
I did try removing the user and password on the MQTT integration, rebotting and running the docker go-rotel command again. But I still got the MQTT connection refused message. I think your suggestion would help.

**Comment by djthorpe** [comment]
Thanks.  Could you share the docker command you are using to run the MQTT broker and then I can also test it myself.

**Comment by nirvine** [comment]
It was set up in Portainer. I hope this is what you need!
![Screenshot 2024-10-14 at 07-45-53 Portainer local](https://github.com/user-attachments/assets/4e12681c-2dae-4f09-84c6-d1b73540763b)
![Screenshot 2024-10-14 at 07-46-17 Portainer local](https://github.com/user-attachments/assets/8f4e037c-7b23-446f-966f-7e466e038db2)


mosquitto.conf file:

> persistence true
> persistence_location /mosquitto/data
> user mosquitto
> listener 1883
> allow_anonymous true
> log_dest file /mosquitto/log/mosquitto.log
> log_dest stdout

**Comment by djthorpe** [comment]
Thank you for providing me with all that information. I now understand that the issue isn't credentials (since you have `allow_anonymous true` in your MQTT broker configuration but with the server address (the `-mqtt localhost:1883` argument). You need to change the docker command to the following:

```
docker run --rm --name rotel --device=/dev/ttyUSB1 \
  ghcr.io/djthorpe/rotel-linux-aarch64:1.0.9 \
  rotel -mqtt ipaddress:1883 -tty /dev/ttyUSB1
 ```
 
Where "ipaddress" is the IP address of your host computer, rather than localhost.  On a local LAN this is often of the format 192.168.XXX.XXX ... but depends on your router. The reason is that "localhost" resolves to inside the container network, rather than routing to the MQTT container.

I did actually add the credentials as well in version v1.0.9 so if you need to use a username/password, that should also be possible now.

Let me know how it goes.

**Comment by djthorpe** [comment]
Great!
