### ISSUE TITLE
Update to V1.0.12 breaks volume, input and select

### ISSUE THREAD

**Issue by nirvine** [djthorpe/go-rotel#25]
I am really sorry to bother you again, but on updating the version I have speaker control, but the other options report unknown or unavailable. 
HA Logs:

> 2024-10-17 10:17:03.841 ERROR (MainThread) [homeassistant.components.switch] Platform mqtt does not generate unique IDs. ID rotel_amp00_power is already used by switch.rotel_amp00 - ignoring switch.rotel_amp00_power
> 2024-10-17 10:17:03.846 ERROR (MainThread) [homeassistant.components.number] Platform mqtt does not generate unique IDs. ID rotel_amp00_volume is already used by number.rotel_amp00 - ignoring number.rotel_amp00_volume
> 2024-10-17 10:17:03.847 ERROR (MainThread) [homeassistant.components.select] Platform mqtt does not generate unique IDs. ID rotel_amp00_input is already used by select.rotel_amp00 - ignoring select.rotel_amp00_input

I have tried removing the MQTT integration, and rebooting the machine, but these errors persist.

**Comment by djthorpe** [comment]
Hi Narelle. It's likely something to do with component re-registration. Not exactly sure why that's happening to be honest, but you can delete the older entities perhaps in Home Assistant and then restart the rotel docker container?

In Home Assistant, maybe go to : Settings->Devices & Services->Entities, search for entities called "amp00" and delete them (they may be hidden, so remove the filter which only shows active entities).

Once you've done that, you could then restart the rotel service. I will see if I can re-create this.

**Comment by nirvine** [comment]
I have deleted all automations and scripts that use the amp, and dashboard cards that reference the entities. But I am still not allowed to delete the entity entries. They disappear when I remove the MQTT integration. 
Steps taken: 
  Stop rotel container. 
  Delete MQTT entry.
  Power off computer. Wait
  Restart computer.
  Add MQTT integration to Home Assistant. Check diagnostics. Rotel entries appear in this file. 
I re-configured MQTT to turn off automatic discovery, and could then delete the entities. 
Reboot computer. (Rotel stopped). 
Check MQTT - no entries. 
Change configuration to allow auto discovery, 5 entities reappear. But volume, power and input still give the same error message - 
  Platform mqtt does not generate unique IDs. ID rotel_amp00_input is already used by select.rotel_amp00 - ignoring select.rotel_amp00_input

I do not know how to completely remove them!

**Comment by djthorpe** [comment]
OK let me add a -id parameter so you can start from scratch, will get back to you later.

**Comment by djthorpe** [comment]
So far I have not been able to replicate this, but please try changing the "amp00" parameter to "amp01" or something like that? The modified command includes a `-id` flag:

```bash
docker run --rm --name rotel --device=/dev/ttyUSB1 \
  ghcr.io/djthorpe/go-rotel-linux-arm64:1.0.14 \
  rotel -mqtt ipaddress:1883 -tty /dev/ttyUSB1 -id amp01
```

You can then create a card in Home Assistant with this new ID:

```yaml
type: entities
entities:
  - entity: switch.rotel_amp01_power
  - entity: number.rotel_amp01_volume
  - entity: select.rotel_amp01_input
  - entity: switch.rotel_amp01_speaker_a
  - entity: switch.rotel_amp01_speaker_b
title: Rotel
show_header_toggle: false
state_color: true
```

Perhaps this would help with the "ID rotel_amp00_input is already used"?

**Comment by nirvine** [comment]
All working smoothly now, as amp01.
Thanks again.

**Comment by djthorpe** [comment]
Thanks for the testing, and glad it's working :-)
